### PR TITLE
fix javascript enabled

### LINKED ISSUE #13: Enable js
`
node-less-chokidar --include-path ./node_modules src/ -o src/ --js
`

`err { [Error: Inline JavaScript is not enabled. Is it set in your options?
`

I Couldn't enable inline js inside less
--js is not working

### PR DESCRIPTION
**Pull request by Rockson**
Closes #13 
Also should be a flag, but probably there is no downside on enabling it by default

### CODE REVIEW

**Comment by notsafe** [comment]
Since the default behavior is disabled, I think you should at least do a check
something like

```
const lessOpts = {
	paths: ['.', path.dirname(options.src)].concat(options.paths),
	sourceMap: {},
	javascriptEnabled: !!options.js
};
```

**Comment by Abazhenov-SCX** [comment]
Any chance of this getting merged soon?

**Comment by Abazhenov** [comment]
Any chance of this getting merged soon?

**Comment by Ragzzy-R** [comment]
Has this been merged to main branch? I get the issue #13 while using ^0.3.1 as I have not ejected my create-react-app, there is no way I can enable Javascript myself.

**Comment by Rockson** [comment]
I think that until this gets merged u can fork my repo and install the package using git url

**Comment by Ragzzy-R** [comment]
Yeah I ended up just changing the code to whatever you did in PR and it works now. thanks man really u are a life saver.

**Pull request merged**
